name: Servoy Build                                                      # Name of the workflow that will appear on the Actions tab in GitHub
on: 
  push:
    branches:
      - examples/DigitaloOcean/containerRegistry   
jobs:                           # Run the build only on this branch
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deployFTP]')"           # Run only if [war] is in the commit message
    steps:
     - name: Checkout                                                   # Checkout the Git repository into the Action runner
       uses: actions/checkout@v2

     - name: Servoy Build                                               # Build the WAR file
       uses: itechpros/servoy-war-builder@v1
       with:
         servoy-version: 2022.03.4.3746
         api-key: ${{ secrets.ALL_PRODUCTS_PACK_KEY }}
         solution-name: cloudSampleSolution
         default-admin-user: ${{ secrets.DEFAULT_ADMIN_USER }}
         default-admin-password: ${{ secrets.DEFAULT_ADMIN_PASSWORD }}
         properties-file: prop_files/servoy.build.properties            # Use servoy.build.properties for the build process (NOT included in the WAR)
         properties-file-war: prop_files/servoy.war.properties          # Use servoy.war.properties for the WAR file (NOT used in the build process)
         dbi: true                                                      # We don't want to open up our firewall for all of GitHub's IPs, so use DBI files instead of trying to connect to the DB
         war-file-name: cloud.war                                       # Override our WAR file name from "HelloWorld.war" to "hello.war"
         allow-sql-keywords: true                                       # Allow columns and tables created via DBIs to contain SQL keywords
         allow-data-model-changes: all                                  # Allow Servoy to modify the database structure to match what's in the DBI files on all database servers
         import-user-policy: 0                                          # Don't import or update any users that are in this repository (resources project)
         extras-folder: ServoyDeveloperExtras                           # Use the folder "ServoyDeveloperExtras" as the folder that contains our extra JARs, drivers, etc. that should be included in the build
         
     - name: deploy file
       uses: wlixcc/SFTP-Deploy-Action@v1.2.4
       with:
         username: ${{ secrets.FTP_USER }}
         password: ${{ secrets.FTP_PASS }}
         server: 'devu.co'
         local_path: 'cloud.war'
         remote_path: '/home/itech_paul/devu.co/temp'
env:
  DIGITALOCEAN_PG_PASSWORD: ${{ secrets.DIGITALOCEAN_PG_PASSWORD }}
